#if OPENGL
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenTK.Graphics.OpenGL4;
using Kokoro3.Math;

namespace Kokoro3.OpenGL
{
    public class TextureView : Texture
    {
        public TextureStorage Parent;
        public int LayerID;

        public Vector2 Size;

        //This can't be constructed instead it's generated by the texture storage, containing a single layer from the texture storage
        internal TextureView(TextureStorage p, Engine.PixelComponentType pct, int minLevel, int numLevels, int layer)
        {
            Parent = p;
            LayerID = layer;
            this.pct = pct;
            this.Size = new Vector2(p.Size.X, p.Size.Y);

            GL.TextureView(ID, TextureTarget.Texture2D, p.ID, EnumConverters.EPixelComponentType(pct), minLevel, numLevels, layer, 1);
        }
    }
}
#endif